[2024-10-29T21:22:49.554+0000] {processor.py:186} INFO - Started process (PID=3034) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:22:49.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:22:49.556+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:22:49.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:22:49.560+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:22:49.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:22:49.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:22:49.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.025 seconds
[2024-10-29T21:23:20.599+0000] {processor.py:186} INFO - Started process (PID=3331) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:20.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:23:20.605+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:23:20.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:20.611+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:23:20.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:23:20.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:20.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.046 seconds
[2024-10-29T21:23:50.826+0000] {processor.py:186} INFO - Started process (PID=3622) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:50.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:23:50.830+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:23:50.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:50.834+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:23:50.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:23:50.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:23:50.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.030 seconds
[2024-10-29T21:24:21.020+0000] {processor.py:186} INFO - Started process (PID=3913) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:21.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:24:21.025+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:24:21.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:21.030+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:24:21.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:24:21.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:21.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.035 seconds
[2024-10-29T21:24:52.075+0000] {processor.py:186} INFO - Started process (PID=4204) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:52.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:24:52.081+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:24:52.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:52.090+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:24:52.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:24:52.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:24:52.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.050 seconds
[2024-10-29T21:25:22.946+0000] {processor.py:186} INFO - Started process (PID=4495) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:22.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:25:22.952+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:25:22.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:22.959+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:25:22.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:25:22.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:22.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.047 seconds
[2024-10-29T21:25:53.857+0000] {processor.py:186} INFO - Started process (PID=4786) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:53.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:25:53.862+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:25:53.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:53.867+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:25:53.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:25:53.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:25:53.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.035 seconds
[2024-10-29T21:26:24.739+0000] {processor.py:186} INFO - Started process (PID=5077) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:24.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:26:24.748+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:26:24.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:24.755+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:26:24.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:26:24.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:24.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.054 seconds
[2024-10-29T21:26:55.787+0000] {processor.py:186} INFO - Started process (PID=5368) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:55.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:26:55.792+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:26:55.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:55.798+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:26:55.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:26:55.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:26:55.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.036 seconds
[2024-10-29T21:27:26.048+0000] {processor.py:186} INFO - Started process (PID=5659) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:26.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:27:26.057+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:27:26.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:26.063+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:27:26.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:27:26.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:26.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.073 seconds
[2024-10-29T21:27:56.322+0000] {processor.py:186} INFO - Started process (PID=5950) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:56.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:27:56.330+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:27:56.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:56.336+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:27:56.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:27:56.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:27:56.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.049 seconds
[2024-10-29T21:28:26.486+0000] {processor.py:186} INFO - Started process (PID=6241) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:26.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:28:26.494+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:28:26.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:26.502+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:28:26.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:28:26.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:26.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.056 seconds
[2024-10-29T21:28:56.655+0000] {processor.py:186} INFO - Started process (PID=6532) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:56.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:28:56.661+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:28:56.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:56.668+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:28:56.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6
    )
     ^
SyntaxError: expected ':'
[2024-10-29T21:28:56.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:28:56.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.042 seconds
[2024-10-29T21:29:23.511+0000] {processor.py:186} INFO - Started process (PID=6823) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:23.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:29:23.519+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:29:23.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:23.534+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:29:23.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 12, in <module>
    "retry_delay": timedelta(seconds=30),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-10-29T21:29:23.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:23.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.079 seconds
[2024-10-29T21:29:50.739+0000] {processor.py:186} INFO - Started process (PID=7108) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:50.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:29:50.746+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:29:50.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:50.758+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:29:50.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 21, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Json to Parquet' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-29T21:29:50.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:29:50.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.058 seconds
[2024-10-29T21:30:20.937+0000] {processor.py:186} INFO - Started process (PID=7399) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:20.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:30:20.942+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:20.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:20.949+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:20.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 21, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Json to Parquet' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-29T21:30:20.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:20.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.043 seconds
[2024-10-29T21:30:26.007+0000] {processor.py:186} INFO - Started process (PID=7410) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:26.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:30:26.012+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:26.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:26.024+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:26.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:30:26.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:26.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.051 seconds
[2024-10-29T21:30:56.384+0000] {processor.py:186} INFO - Started process (PID=7700) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:56.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:30:56.389+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:56.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:56.394+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:30:56.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:30:56.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:30:56.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.039 seconds
[2024-10-29T21:31:26.792+0000] {processor.py:186} INFO - Started process (PID=7991) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:26.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:31:26.799+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:31:26.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:26.806+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:31:26.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:31:26.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:26.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.053 seconds
[2024-10-29T21:31:56.989+0000] {processor.py:186} INFO - Started process (PID=8282) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:56.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:31:56.994+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:31:56.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:56.999+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:31:56.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:31:57.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:31:57.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.039 seconds
[2024-10-29T21:32:27.347+0000] {processor.py:186} INFO - Started process (PID=8573) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:27.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:32:27.353+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:32:27.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:27.360+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:32:27.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:32:27.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:27.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.044 seconds
[2024-10-29T21:32:57.606+0000] {processor.py:186} INFO - Started process (PID=8864) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:57.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:32:57.613+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:32:57.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:57.619+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:32:57.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:32:57.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:32:57.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.051 seconds
[2024-10-29T21:33:27.896+0000] {processor.py:186} INFO - Started process (PID=9155) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:27.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:33:27.904+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:33:27.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:27.912+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:33:27.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:33:27.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:27.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.080 seconds
[2024-10-29T21:33:58.221+0000] {processor.py:186} INFO - Started process (PID=9446) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:58.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:33:58.229+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:33:58.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:58.236+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:33:58.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:33:58.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:33:58.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.052 seconds
[2024-10-29T21:34:28.536+0000] {processor.py:186} INFO - Started process (PID=9737) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:28.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:34:28.547+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:34:28.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:28.559+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:34:28.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 4, in <module>
    from ..etl.json_to_duckdb import JsonToDuck
ImportError: attempted relative import with no known parent package
[2024-10-29T21:34:28.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:28.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.128 seconds
[2024-10-29T21:34:37.716+0000] {processor.py:186} INFO - Started process (PID=9742) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:37.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:34:37.727+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:34:37.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:37.778+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:34:37.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:34:37.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:34:37.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.113 seconds
[2024-10-29T21:35:08.214+0000] {processor.py:186} INFO - Started process (PID=10033) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:08.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:35:08.224+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:08.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:08.238+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:08.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:35:08.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:08.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.086 seconds
[2024-10-29T21:35:13.594+0000] {processor.py:186} INFO - Started process (PID=10268) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:13.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:35:13.603+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:13.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:13.617+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:13.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:35:13.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:13.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.097 seconds
[2024-10-29T21:35:19.677+0000] {processor.py:186} INFO - Started process (PID=10323) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:19.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:35:19.683+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:19.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:19.712+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:19.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:35:19.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:19.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.081 seconds
[2024-10-29T21:35:36.019+0000] {processor.py:186} INFO - Started process (PID=10334) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:36.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:35:36.036+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:36.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:36.067+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:36.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:35:36.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:36.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.151 seconds
[2024-10-29T21:35:46.099+0000] {processor.py:186} INFO - Started process (PID=10619) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:46.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:35:46.103+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:46.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:46.112+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:35:46.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:35:46.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:35:46.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.048 seconds
[2024-10-29T21:36:17.072+0000] {processor.py:186} INFO - Started process (PID=10910) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:17.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:36:17.075+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:36:17.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:17.084+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:36:17.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:36:17.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:17.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.031 seconds
[2024-10-29T21:36:47.126+0000] {processor.py:186} INFO - Started process (PID=11201) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:47.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:36:47.128+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:36:47.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:47.134+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:36:47.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:36:47.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:36:47.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.024 seconds
[2024-10-29T21:37:17.746+0000] {processor.py:186} INFO - Started process (PID=11442) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:17.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:37:17.753+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:37:17.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:17.769+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:37:17.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:37:17.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:17.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.050 seconds
[2024-10-29T21:37:48.703+0000] {processor.py:186} INFO - Started process (PID=11732) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:48.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:37:48.710+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:37:48.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:48.724+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:37:48.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:37:48.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:37:48.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.045 seconds
[2024-10-29T21:38:13.544+0000] {processor.py:186} INFO - Started process (PID=11792) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:13.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:38:13.562+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:38:13.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:13.586+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:38:13.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:38:13.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:13.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.112 seconds
[2024-10-29T21:38:44.105+0000] {processor.py:186} INFO - Started process (PID=12083) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:44.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:38:44.114+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:38:44.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:44.146+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:38:44.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:38:44.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:38:44.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.084 seconds
[2024-10-29T21:39:14.479+0000] {processor.py:186} INFO - Started process (PID=12374) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:14.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:39:14.486+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:39:14.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:14.506+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:39:14.503+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:39:14.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:14.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.086 seconds
[2024-10-29T21:39:44.740+0000] {processor.py:186} INFO - Started process (PID=12665) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:44.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:39:44.750+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:39:44.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:44.764+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:39:44.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:39:44.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:39:44.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.080 seconds
[2024-10-29T21:40:15.180+0000] {processor.py:186} INFO - Started process (PID=12956) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:15.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:40:15.189+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:40:15.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:15.213+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:40:15.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:40:15.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:15.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.084 seconds
[2024-10-29T21:40:46.187+0000] {processor.py:186} INFO - Started process (PID=13247) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:46.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:40:46.203+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:40:46.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:46.217+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:40:46.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:40:46.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:40:46.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.089 seconds
[2024-10-29T21:41:06.264+0000] {processor.py:186} INFO - Started process (PID=13538) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:06.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:41:06.280+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:41:06.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:06.295+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:41:06.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:41:06.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:06.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.087 seconds
[2024-10-29T21:41:34.392+0000] {processor.py:186} INFO - Started process (PID=13829) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:34.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:41:34.400+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:41:34.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:34.413+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:41:34.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:41:34.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:41:34.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.071 seconds
[2024-10-29T21:42:04.677+0000] {processor.py:186} INFO - Started process (PID=14120) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:04.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:42:04.686+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:42:04.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:04.701+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:42:04.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:42:04.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:04.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.077 seconds
[2024-10-29T21:42:35.814+0000] {processor.py:186} INFO - Started process (PID=14411) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:35.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:42:35.822+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:42:35.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:35.848+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:42:35.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:42:35.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:42:35.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.085 seconds
[2024-10-29T21:43:06.527+0000] {processor.py:186} INFO - Started process (PID=14702) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:06.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:43:06.533+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:06.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:06.561+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:06.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:43:06.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:06.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.078 seconds
[2024-10-29T21:43:26.238+0000] {processor.py:186} INFO - Started process (PID=14943) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:26.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:43:26.246+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:26.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:26.262+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:26.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:43:26.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:26.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.104 seconds
[2024-10-29T21:43:31.174+0000] {processor.py:186} INFO - Started process (PID=14998) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:31.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:43:31.181+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:31.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:31.211+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:31.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:43:31.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:31.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.103 seconds
[2024-10-29T21:43:40.300+0000] {processor.py:186} INFO - Started process (PID=15003) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:40.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:43:40.305+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:40.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:40.317+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:43:40.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:43:40.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:43:40.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.064 seconds
[2024-10-29T21:44:10.686+0000] {processor.py:186} INFO - Started process (PID=15294) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:44:10.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:44:10.700+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:44:10.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:44:10.714+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:44:10.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:44:10.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:44:10.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.085 seconds
[2024-10-29T21:45:20.248+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:20.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:45:20.255+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:45:20.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:20.284+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:45:20.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 5, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:45:20.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:20.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.075 seconds
[2024-10-29T21:45:50.512+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:50.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:45:50.518+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:45:50.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:50.532+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:45:50.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 5, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:45:50.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:45:50.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.065 seconds
[2024-10-29T21:46:21.098+0000] {processor.py:186} INFO - Started process (PID=762) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:21.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:46:21.105+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:46:21.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:21.121+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:46:21.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 5, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:46:21.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:21.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.070 seconds
[2024-10-29T21:46:51.848+0000] {processor.py:186} INFO - Started process (PID=1053) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:51.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:46:51.858+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:46:51.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:51.871+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:46:51.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 5, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:46:51.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:46:51.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.076 seconds
[2024-10-29T21:47:08.232+0000] {processor.py:186} INFO - Started process (PID=1344) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:08.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:47:08.240+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:08.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:08.255+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:08.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:47:08.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:08.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.070 seconds
[2024-10-29T21:47:19.439+0000] {processor.py:186} INFO - Started process (PID=1349) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:19.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:47:19.449+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:19.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:19.479+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:19.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:47:19.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:19.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.129 seconds
[2024-10-29T21:47:33.944+0000] {processor.py:186} INFO - Started process (PID=1640) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:33.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:47:33.951+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:33.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:33.965+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:47:33.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:47:33.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:47:34.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.070 seconds
[2024-10-29T21:48:04.792+0000] {processor.py:186} INFO - Started process (PID=1931) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:04.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:48:04.796+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:48:04.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:04.806+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:48:04.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:48:04.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:04.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.040 seconds
[2024-10-29T21:48:34.983+0000] {processor.py:186} INFO - Started process (PID=2222) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:34.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:48:34.987+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:48:34.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:34.997+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:48:34.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:48:34.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:48:35.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.087 seconds
[2024-10-29T21:49:05.581+0000] {processor.py:186} INFO - Started process (PID=2513) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:05.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:49:05.585+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:49:05.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:05.594+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:49:05.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:49:05.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:05.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.035 seconds
[2024-10-29T21:49:35.831+0000] {processor.py:186} INFO - Started process (PID=2804) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:35.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:49:35.833+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:49:35.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:35.841+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:49:35.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:49:35.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:49:35.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.030 seconds
[2024-10-29T21:50:06.244+0000] {processor.py:186} INFO - Started process (PID=3095) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:06.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:50:06.247+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:50:06.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:06.255+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:50:06.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:50:06.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:06.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.038 seconds
[2024-10-29T21:50:36.566+0000] {processor.py:186} INFO - Started process (PID=3386) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:36.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:50:36.570+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:50:36.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:36.578+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:50:36.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:50:36.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:50:36.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.035 seconds
[2024-10-29T21:51:07.005+0000] {processor.py:186} INFO - Started process (PID=3677) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:07.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:51:07.009+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:51:07.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:07.017+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:51:07.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:51:07.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:07.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.032 seconds
[2024-10-29T21:51:37.230+0000] {processor.py:186} INFO - Started process (PID=3968) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:37.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:51:37.233+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:51:37.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:37.241+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:51:37.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:51:37.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:51:37.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.034 seconds
[2024-10-29T21:52:07.698+0000] {processor.py:186} INFO - Started process (PID=4259) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:52:07.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:52:07.701+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:52:07.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:52:07.709+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:52:07.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:52:07.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:52:07.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.031 seconds
[2024-10-29T21:53:26.191+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:26.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:53:26.199+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:53:26.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:26.220+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:53:26.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:53:26.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:26.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.061 seconds
[2024-10-29T21:53:56.817+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:56.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:53:56.828+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:53:56.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:56.847+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:53:56.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:53:56.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:53:56.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.079 seconds
[2024-10-29T21:54:27.172+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:27.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:54:27.182+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:54:27.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:27.206+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:54:27.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:54:27.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:27.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.098 seconds
[2024-10-29T21:54:57.341+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:57.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:54:57.351+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:54:57.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:57.361+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:54:57.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:54:57.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:54:57.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.067 seconds
[2024-10-29T21:55:27.718+0000] {processor.py:186} INFO - Started process (PID=1338) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:27.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:55:27.725+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:55:27.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:27.736+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:55:27.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:55:27.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:27.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.085 seconds
[2024-10-29T21:55:58.541+0000] {processor.py:186} INFO - Started process (PID=1629) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:58.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:55:58.553+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:55:58.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:58.572+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:55:58.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:55:58.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:55:58.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.092 seconds
[2024-10-29T21:56:29.152+0000] {processor.py:186} INFO - Started process (PID=1920) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:29.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:56:29.160+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:56:29.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:29.178+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:56:29.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:56:29.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:29.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.077 seconds
[2024-10-29T21:56:59.925+0000] {processor.py:186} INFO - Started process (PID=2211) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:59.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:56:59.934+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:56:59.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:59.944+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:56:59.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:56:59.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:56:59.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.061 seconds
[2024-10-29T21:57:30.028+0000] {processor.py:186} INFO - Started process (PID=2502) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:57:30.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:57:30.034+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:57:30.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:57:30.047+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:57:30.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:57:30.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:57:30.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.056 seconds
[2024-10-29T21:58:00.315+0000] {processor.py:186} INFO - Started process (PID=2793) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:00.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:58:00.322+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:58:00.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:00.333+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:58:00.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:58:00.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:00.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.057 seconds
[2024-10-29T21:58:30.665+0000] {processor.py:186} INFO - Started process (PID=3084) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:30.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:58:30.681+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:58:30.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:30.692+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:58:30.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:58:30.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:58:30.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.085 seconds
[2024-10-29T21:59:00.870+0000] {processor.py:186} INFO - Started process (PID=3375) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:00.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:59:00.880+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:59:00.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:00.895+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:59:00.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:59:00.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:00.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.085 seconds
[2024-10-29T21:59:31.351+0000] {processor.py:186} INFO - Started process (PID=3666) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:31.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T21:59:31.359+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:59:31.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:31.377+0000] {logging_mixin.py:190} INFO - [2024-10-29T21:59:31.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T21:59:31.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T21:59:31.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.095 seconds
[2024-10-29T22:00:01.785+0000] {processor.py:186} INFO - Started process (PID=3956) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:00:01.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T22:00:01.805+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:00:01.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:00:01.855+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:00:01.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T22:00:01.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:00:01.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.162 seconds
[2024-10-29T22:02:15.289+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:15.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T22:02:15.294+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:02:15.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:15.338+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:02:15.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T22:02:15.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:15.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.083 seconds
[2024-10-29T22:02:46.298+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:46.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/json_duck_etl.py for tasks to queue
[2024-10-29T22:02:46.305+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:02:46.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:46.316+0000] {logging_mixin.py:190} INFO - [2024-10-29T22:02:46.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/json_duck_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/json_duck_etl.py", line 6, in <module>
    from etl.json_to_duckdb import JsonToDuck
  File "/opt/airflow/dags/etl/json_to_duckdb.py", line 17, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2024-10-29T22:02:46.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/json_duck_etl.py
[2024-10-29T22:02:46.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/json_duck_etl.py took 0.071 seconds
